version: '3.9'
services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - .:/backend
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 16384M
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]